# Generated by Django 4.2.6 on 2023-10-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0002_shipment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="number",
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
